#!/usr/bin/env bash

# env

HERE="$(dirname "$(readlink -f "${0}")")"

# Use privately bundled apt-get and dpkg-deb if available; can be got on trusty using
# apt download apt libapt-pkg4.12 libbz2-1.0 liblzma5 multiarch-support zlib1g dpkg
if [ -e "${HERE}/libunionpreload.so" ] ; then
  export UNION_PRELOAD="${HERE}"
  export LD_PRELOAD="${HERE}/libunionpreload.so"
  export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
  export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
  export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
fi

# Specify a certain commit if you do not want to use master
# by using:
# export PKG2AICOMMIT=<git sha>
if [ -z "$PKG2AICOMMIT" ] ; then
  PKG2AICOMMIT=master
fi

usage() {
  if [ -z "$APPIMAGE" ]  ; then
    MYSELF="$0"
  else
    MYSELF="$APPIMAGE"
  fi
  echo "usage:"
  echo "  $MYSELF [--no-di] META-NAME|YAMLFILE"
  echo ""
  echo "options:"
  echo "  --di    enable legacy desktop integration (unsupported)"
  exit 1
}

if [ $# -eq 0 ] || [ "x${!#}" = "x--di" ] ; then
  usage
fi
if [ $# -eq 2 ] && [ "x$1" != "x--di" ] ; then
  usage
fi

if [ "x$1" = "x--di" ] ; then
  ENABLE_DI="yes"
else
  ENABLE_DI="no"
fi
